{% set version = "2.12.1" %}

package:
  name: tensorboard
  version: {{ version }}

source:
  git_url: https://github.com/tensorflow/tensorboard.git
  git_rev: {{ version }}
  patches:
    - 0005-PSIRT-PVR0214103-for-bleach.patch
    - 0006-Update-rules_apple-and-apple_support.patch
    - 0001-Updated-rules_nodejs.patch

build:
  number: 2
  noarch: python
  string: pyh{{ PKG_HASH }}_pb{{ protobuf | replace(".*", "")}}_{{ PKG_BUILDNUM }}
  # Make sure there is no tensorboard entry point in the tensorflow-{gpu-,}base
  # packages as it conflicts with a file in this package.
  entry_points:
    - tensorboard = tensorboard.main:run_main

requirements:
  build:
    - {{ compiler('c') }}       #[ppc_arch != 'p10']
    - {{ compiler('cxx') }}     #[ppc_arch != 'p10']
  host:
    - bazel {{ bazel }} 
    - python # noarch package; don't tie to specific python version
    - numpy {{ numpy }}
    - absl-py {{ absl_py }}
    - tensorboard-data-server {{ tensorboard_data_server }}
    - protobuf {{ protobuf }}
  run:
    - python # noarch package; don't tie to specific python version
    - absl-py {{ absl_py }}
    - google-auth {{ google_auth }}
    - google-auth-oauthlib {{ google_auth_oauthlib }}
    - grpcio {{ grpcio }}
    - markdown {{ markdown }}
    - numpy {{ numpy }}
    - protobuf {{ protobuf }}
    - requests {{ requests }}
    - setuptools {{ setuptools }}
    - six {{ six }}
    - tensorboard-plugin-wit {{ tensorboard_plugin_wit }}
    - werkzeug {{ werkzeug }}
    - tensorboard-data-server {{ tensorboard_data_server }}
    - wheel
    - packaging

test:
  imports:
    - tensorboard
  commands:
    - tensorboard --help

about:
  home: http://tensorflow.org/
  license: Apache-2.0
  license_family: Apache
  license_file: {{ SRC_DIR }}/LICENSE
  summary: TensorFlow's Visualization Toolkit.
  description: |
    TensorBoard is a suite of web applications for inspecting and understanding
    your TensorFlow runs and graphs.
  dev_url: https://github.com/tensorflow/tensorboard

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
